"""empty message

Revision ID: 2405061945c
Revises: None
Create Date: 2014-01-14 16:33:41.214678

"""

# revision identifiers, used by Alembic.
revision = '2405061945c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
