"""empty message

Revision ID: 2f9c3f026b5
Revises: 2405061945c
Create Date: 2014-01-16 17:47:01.173216

"""

# revision identifiers, used by Alembic.
revision = '2f9c3f026b5'
down_revision = '2405061945c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
